version = 1

[envs.core-utils]
channels = ["conda-forge"]
dependencies = { stow = "*", ripgrep = "*", fd-find = "*", bat = "*", zoxide = "*", eza = "*", git = "*", neovim = "*", starship = "*" }
exposed = { stow = "stow", rg = "rg", fd = "fd", bat = "bat", zoxide = "zoxide", eza = "eza", git = "git", nvim = "nvim", starship = "starship" }
