#!/usr/bin/env bash
text="$(xsel -o)"
translate="$(trans -b :en $text)"
echo -e "Original text:" "$text"'\n' > /tmp/notitrans
echo "Translation:" "$translate" >> /tmp/notitrans
zenity --text-info --title="Translation" --filename=/tmp/notitrans