[tasks.test-pressing]
env = { "LOG_LEVEL" = "debug" }
command = "cargo"
args = [
  "run",
  "--",
  "-c",
  "pressing.cookies.json",
  "-f",
  "test.txt",
  "--logfile",
  "test.log",
  "-w",
  "5m",
  "-t",
  "15m",
  "--standalone",
  "--headful",
]
