// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © InNoobWeTrust

//@version=6
indicator("Relative Structure Strength Index", overlay = false)

import TradingView/ta/10
import forbidden_gun/commonlib/6
import forbidden_gun/ma_lib/3

//===============================================================================
// Settings
//===============================================================================
tf = input.timeframe('','► Timeframe')

threshold_grp = '► Thresholds'
threshold_low_limit = input.float(30,'Low threshold',minval=0,maxval=50,group = threshold_grp)
threshold_high_limit = input.float(70,'High threshold',minval=50,maxval=100,group = threshold_grp)
threshold_color_inline = 'Threshold colors (middle line to low/high)'
threshold_color_middle_low = input.color(color.new(color.blue,90),threshold_color_inline,group = threshold_grp,inline = threshold_color_inline)
threshold_color_middle_high = input.color(color.new(color.yellow,90),'',group = threshold_grp,inline = threshold_color_inline)

rssi_grp = '► RSSI'
rssi_len = input.int(14,'RSSI length',group = rssi_grp)
rssi_ma_inline = 'RSSI MA'
rssi_ma_type = input.enum(ma_lib.MaT.wma,rssi_ma_inline,group = rssi_grp,inline = rssi_ma_inline)
rssi_ma_len = input.int(9,'',group = rssi_grp,inline = rssi_ma_inline)
bearish_color = input.color(color.new(color.red,50),'Bearish area color',group = rssi_grp)
bullish_color = input.color(color.new(color.green,50),'Bullish area color',group = rssi_grp)

bg_grp = '► Bullish/bearish background'
bg_enable = input.bool(true,'Enable',group = bg_grp)
bg_overlay = input.bool(false,'Overlay',group = bg_grp)
bg_color_inline = 'Background colors (bullish/bearish)'
bg_bullish_color = input.color(color.new(color.aqua,70),bg_color_inline,group = bg_grp,inline = bg_color_inline)
bg_bearish_color = input.color(color.new(color.orange,70),'',group = bg_grp,inline = bg_color_inline)

sw_grp = '► Sideway thresholds'
sw_high_inline = 'High threshold'
sw_high_enable = input.bool(true,sw_high_inline,group = sw_grp,inline = sw_high_inline)
sw_high_threshold = input.int(60,'',group = sw_grp,inline = sw_high_inline)
sw_high_bg_color = input.color(color.new(color.maroon,80),'',group = sw_grp,inline = sw_high_inline)
sw_low_inline = 'Low threshold'
sw_low_enable = input.bool(true,sw_low_inline,group = sw_grp,inline = sw_low_inline)
sw_low_threshold = input.int(40,'',group = sw_grp,inline = sw_low_inline)
sw_low_bg_color = input.color(color.new(color.navy,80),'',group = sw_grp,inline = sw_low_inline)

//===============================================================================
// Calculation
//===============================================================================

[bar_pwr, bias] = commonlib.bar_structure()

rssi = ta.rsi(bar_pwr, rssi_len)
rssi_ma = ma_lib.ma(rssi_ma_type,rssi,rssi_ma_len)
rssi := request.security(syminfo.tickerid,tf,rssi)
rssi_ma := request.security(syminfo.tickerid,tf,rssi_ma)
bullish_area_color = rssi_ma >= sw_high_threshold ? bullish_color : na
bearish_area_color = rssi_ma <= sw_low_threshold ? bearish_color : na
bg_color = switch
	bg_enable and rssi_ma <= threshold_low_limit => bg_bearish_color
	bg_enable and rssi_ma >= threshold_high_limit => bg_bullish_color
	=> color(na)

//===============================================================================
// Plot
//===============================================================================

// Thresholds
low_line = hline(threshold_low_limit,'Index Low threshold',linestyle = hline.style_dashed,color=color.new(color.gray,50))
middle_line = hline(50,'Index Middle',linestyle = hline.style_dashed,color=color.new(color.gray,50))
high_line = hline(threshold_high_limit,'Index High threshold',linestyle = hline.style_dashed,color=color.new(color.gray,50))
fill(low_line,middle_line,threshold_color_middle_low)
fill(high_line,middle_line,threshold_color_middle_high)

// Sideway thresholds
sw_low_line = hline(sw_low_threshold,'Sideway low threshold',linestyle = hline.style_dotted,color = color.new(color.gray,70))
sw_high_line = hline(sw_high_threshold,'Sideway high threshold',linestyle = hline.style_dotted,color = color.new(color.gray,70))
fill(sw_low_line,middle_line,sw_low_bg_color)
fill(sw_high_line,middle_line,sw_high_bg_color)

// RSSI
plot(rssi,'RSSI',color.new(color.purple,50),force_overlay = false)
plot(rssi_ma,'RSSI MA', color.yellow,force_overlay = false)
plot(rssi_ma,'Bearish',bearish_area_color,style = plot.style_area,histbase = sw_low_threshold)
plot(rssi_ma,'Bullish',bullish_area_color,style = plot.style_area,histbase = sw_high_threshold)

// Panel background
bgcolor(bg_overlay ? bg_color : color(na),force_overlay = true)
bgcolor(bg_overlay ? color(na) : bg_color,force_overlay = false)